# Generated by Django 3.2.16 on 2022-11-11 12:39

import apps.home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brgy_info',
            name='brgy_contactNo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='brgy_info',
            name='brgy_logo',
            field=models.ImageField(default='brgy_info/logo.png', storage=apps.home.storage.OverwriteStorage, upload_to=None),
        ),
    ]
