# Generated by Django 3.2.16 on 2022-11-11 14:02

import apps.home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221111_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='purok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purok_name', models.CharField(max_length=50)),
                ('purok_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='brgy_info',
            name='brgy_logo',
            field=models.ImageField(default='brgy_info/default.png', storage=apps.home.storage.OverwriteStorage, upload_to=None),
        ),
    ]
