# Generated by Django 3.2.16 on 2022-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221111_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purok',
            name='purok_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
