# Generated by Django 3.2.16 on 2022-11-13 02:06

import apps.home.models
import apps.home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221113_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='res_isVoter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='res_photo',
            field=models.ImageField(blank=True, null=True, storage=apps.home.storage.OverwriteStorage(), upload_to=apps.home.models.resPhoto_path),
        ),
    ]
