# Generated by Django 3.2.16 on 2022-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221113_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='res_isVoter',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
    ]
