# Generated by Django 3.2.16 on 2022-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_resident_res_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purok',
            name='purok_description',
            field=models.TextField(blank=True),
        ),
    ]
